code --install-extension 1yib.nodejs-bundle
code --install-extension 1yib.svelte-bundle
code --install-extension aaron-bond.better-comments
code --install-extension adpyke.codesnap
code --install-extension adrianwilczynski.add-reference
code --install-extension adrianwilczynski.asp-net-core-switcher
code --install-extension adrianwilczynski.blazor-snippet-pack
code --install-extension adrianwilczynski.csharp-to-typescript
code --install-extension adrianwilczynski.libman
code --install-extension adrianwilczynski.namespace
code --install-extension adrianwilczynski.terminal-commands
code --install-extension adrianwilczynski.toggle-hidden
code --install-extension adrianwilczynski.user-secrets
code --install-extension akamud.vscode-theme-onedark
code --install-extension aksharpatel47.vscode-flutter-helper
code --install-extension albertopdrf.root-file-viewer
code --install-extension alefragnani.bookmarks
code --install-extension alefragnani.project-manager
code --install-extension alexisvt.flutter-snippets
code --install-extension andrijarubelj.flutterpubopen
code --install-extension angelomollame.conflict-squeezer
code --install-extension antonydalmiere.android-support
code --install-extension anysphere.pyright
code --install-extension ardenivanov.svelte-intellisense
code --install-extension atlassian.atlascode
code --install-extension batisteo.vscode-django
code --install-extension bbenoist.shell
code --install-extension bierner.markdown-yaml-preamble
code --install-extension brunolm.export-index
code --install-extension castwide.solargraph
code --install-extension chflick.firecode
code --install-extension chris-noring.node-snippets
code --install-extension christian-kohler.npm-intellisense
code --install-extension christian-kohler.path-intellisense
code --install-extension circlecodesolution.ccs-flutter-color
code --install-extension cmstead.js-codeformer
code --install-extension cmstead.jsrefactor
code --install-extension codezombiech.gitignore
code --install-extension compulim.vscode-clock
code --install-extension cseelye.vscode-allofthem
code --install-extension dart-code.dart-code
code --install-extension dart-code.flutter
code --install-extension dbaeumer.vscode-eslint
code --install-extension dionmunk.vscode-notes
code --install-extension doggy8088.netcore-editorconfiggenerator
code --install-extension doggy8088.netcore-extension-pack
code --install-extension doggy8088.netcore-snippets
code --install-extension doggy8088.quicktype-refresh
code --install-extension dongli.python-preview
code --install-extension donjayamanne.git-extension-pack
code --install-extension donjayamanne.githistory
code --install-extension donjayamanne.python-environment-manager
code --install-extension donjayamanne.python-extension-pack
code --install-extension dotjoshjohnson.xml
code --install-extension dracula-theme.theme-dracula
code --install-extension eamodio.gitlens
code --install-extension editorconfig.editorconfig
code --install-extension eg2.vscode-npm-script
code --install-extension esbenp.prettier-vscode
code --install-extension esentis.flutter-find-unused-assets-and-dart-files
code --install-extension evils.vscode-flutter-riverpod-helper
code --install-extension fabiospampinato.vscode-open-in-github
code --install-extension felixangelov.bloc
code --install-extension fivethree.vscode-fastlane-snippets
code --install-extension fivethree.vscode-svelte-snippets
code --install-extension flimberger.android-system-tools
code --install-extension flutterando.flutter-coverage
code --install-extension formulahendry.auto-rename-tag
code --install-extension formulahendry.dotnet
code --install-extension formulahendry.dotnet-test-explorer
code --install-extension formulahendry.github-actions
code --install-extension franneck94.c-cpp-runner
code --install-extension fwcd.kotlin
code --install-extension gaetschwartz.build-runner
code --install-extension github.copilot
code --install-extension github.copilot-chat
code --install-extension github.github-vscode-theme
code --install-extension github.vscode-codeql
code --install-extension github.vscode-github-actions
code --install-extension github.vscode-pull-request-github
code --install-extension gmlewis-vscode.flutter-stylizer
code --install-extension groksrc.ruby
code --install-extension gruntfuggly.save-without-format
code --install-extension gruntfuggly.todo-tree
code --install-extension hbenl.vscode-test-explorer
code --install-extension henoc.svgeditor
code --install-extension hossammourad.vscode-get-color-name
code --install-extension hridoy.rails-snippets
code --install-extension humao.rest-client
code --install-extension hzgood.dart-data-class-generator
code --install-extension ionide.ionide-fsharp
code --install-extension irongeek.vscode-env
code --install-extension itarato.byesig
code --install-extension jasonnutter.search-node-modules
code --install-extension jeroen-meijer.pubspec-assist
code --install-extension jerrygoyal.shortcut-menu-bar
code --install-extension jmrog.vscode-nuget-package-manager
code --install-extension jock.svg
code --install-extension k--kato.docomment
code --install-extension kasik96.swift
code --install-extension kelvin.vscode-sshfs
code --install-extension kevinchatham.openwithcode
code --install-extension kevinrose.vsc-python-indent
code --install-extension kinolaev.git-lfs-file-locking
code --install-extension kisstkondoros.vscode-codemetrics
code --install-extension koichisasada.vscode-rdbg
code --install-extension kortina.run-in-terminal
code --install-extension kreativ-software.csharpextensions
code --install-extension lacroixdavid1.vscode-format-context-menu
code --install-extension lehni.vscode-fix-checksums
code --install-extension leizongmin.node-module-intellisense
code --install-extension lottiefiles.vscode-lottie
code --install-extension marcelovelasquez.flutter-tree
code --install-extension mateocerquetella.xcode-12-theme
code --install-extension matheuslessa.maestro
code --install-extension matthiaskuech.run-script
code --install-extension mbehr1.vsc-lfs
code --install-extension me-dutour-mathieu.vscode-github-actions
code --install-extension mhutchie.git-graph
code --install-extension miguel-savignano.ruby-symbols
code --install-extension miladatef.hive-snippets
code --install-extension miquelddg.dart-barrel-file-generator
code --install-extension miramac.vscode-exec-node
code --install-extension mohsen1.prettify-json
code --install-extension moyu.snapcode
code --install-extension ms-dotnettools.csdevkit
code --install-extension ms-dotnettools.csharp
code --install-extension ms-dotnettools.dotnet-interactive-vscode
code --install-extension ms-dotnettools.vscode-dotnet-pack
code --install-extension ms-dotnettools.vscode-dotnet-runtime
code --install-extension ms-dotnettools.vscodeintellicode-csharp
code --install-extension ms-python.debugpy
code --install-extension ms-python.isort
code --install-extension ms-python.python
code --install-extension ms-python.vscode-pylance
code --install-extension ms-toolsai.jupyter
code --install-extension ms-toolsai.jupyter-renderers
code --install-extension ms-toolsai.vscode-jupyter-cell-tags
code --install-extension ms-toolsai.vscode-jupyter-slideshow
code --install-extension ms-vscode.cmake-tools
code --install-extension ms-vscode.cpptools
code --install-extension ms-vscode.cpptools-extension-pack
code --install-extension ms-vscode.cpptools-themes
code --install-extension ms-vscode.live-server
code --install-extension ms-vscode.test-adapter-converter
code --install-extension ms-vsliveshare.vsliveshare
code --install-extension mthuong.vscode-flutter-freezed-helper
code --install-extension nanlei.save-all
code --install-extension nash.awesome-flutter-snippets
code --install-extension natqe.reload
code --install-extension nicolasvuillamy.vscode-groovy-lint
code --install-extension njpwerner.autodocstring
code --install-extension nolancorcoran.dart-exports
code --install-extension oderwat.indent-rainbow
code --install-extension omartawfik.github-actions-vscode
code --install-extension orestesgaolin.dart-export-index
code --install-extension orta.vscode-ios-common-files
code --install-extension oscarcs.dart-syntax-highlighting-only
code --install-extension panuavakul.mvvm-flutter-widget
code --install-extension patcx.vscode-nuget-gallery
code --install-extension pbeast.lanes-navigator
code --install-extension pflannery.vscode-versionlens
code --install-extension pieterjongsma.swift-playgrounds
code --install-extension piyushvscode.nodejs-snippets
code --install-extension pkief.material-icon-theme
code --install-extension postman.postman-for-vscode
code --install-extension pythonhub.riverpodsnippets
code --install-extension quicktype.quicktype
code --install-extension redhat.vscode-xml
code --install-extension redhat.vscode-yaml
code --install-extension remcoros.startanyshell
code --install-extension robert-brunhage.flutter-riverpod-snippets
code --install-extension rvest.vs-code-prettier-eslint
code --install-extension sergelamikhov.lcov-lang
code --install-extension shaharkazaz.git-merger
code --install-extension shopify.ruby-extensions-pack
code --install-extension shopify.ruby-lsp
code --install-extension shyykoserhiy.vscode-spotify
code --install-extension simonsiefke.svg-preview
code --install-extension smockle.xcode-default-theme
code --install-extension sorbet.sorbet-vscode-extension
code --install-extension sswg.swift-lang
code --install-extension standard.vscode-standard
code --install-extension steoates.autoimport
code --install-extension streetsidesoftware.code-spell-checker
code --install-extension svelte.svelte-vscode
code --install-extension testdouble.vscode-standard-ruby
code --install-extension timonwong.shellcheck
code --install-extension tomzx.run-me
code --install-extension toroxx.vscode-avdmanager
code --install-extension trabpukcip.vscode-npm-scripts
code --install-extension twxs.cmake
code --install-extension tyriar.shell-launcher
code --install-extension usernamehw.errorlens
code --install-extension vadimcn.vscode-lldb
code --install-extension vikas.code-navigation
code --install-extension visualstudioexptteam.intellicode-api-usage-examples
code --install-extension visualstudioexptteam.vscodeintellicode
code --install-extension vknabel.vscode-apple-swift-format
code --install-extension vladmrnv.expresssnippet
code --install-extension volynetsserhii.get-color-name
code --install-extension vscode-snippet.snippet
code --install-extension waderyan.gitblame
code --install-extension wayou.vscode-todo-highlight
code --install-extension weekit.flutter-assets-gen2
code --install-extension wholroyd.jinja
code --install-extension withfig.fig
code --install-extension xabikos.javascriptsnippets
code --install-extension yamajyn.commandlist
code --install-extension yashpaneliya.fast-dart
code --install-extension yatki.vscode-surround
code --install-extension yt1997kt.flutter-bloc
code --install-extension zainchen.json
code --install-extension zhuangtongfa.material-theme
code --install-extension ziyasal.vscode-open-in-github
code --install-extension zxh404.vscode-proto3
