default_platform(:ios)

VERSION_NUMBER = "3.0.0"

platform :ios do
  before_all do
  end
  desc "Push a new beta build to TestFlight"
  lane :beta do
  enable_automatic_code_signing

  increment_version_number(
    version_number: VERSION_NUMBER
  )

  increment_build_number({
      build_number: latest_testflight_build_number + 1
  })

    gym(scheme: "Runner",
          xcargs: "-allowProvisioningUpdates",
    )
    upload_to_testflight
  end
end
