default_platform(:android)


APP_TRACK_INTERNAL = "internal"
APP_JSON_KEY = "./fastlane/secret/google_play.json"
APP_BUNDLE_PATH = "../build/app/outputs/bundle/release/app-release.aab"
VERSION_NUMBER = "3.0.0"

platform :android do
  lane :release do |options|
      versionCode =  google_play_track_version_codes(track: APP_TRACK_INTERNAL)[0] + 1
     flutter_build_appBundle(VERSION_NUMBER,versionCode)
     upload_to_play_store(
      root_url: "https://androidpublisher.googleapis.com/",
      track: APP_TRACK_INTERNAL,
      json_key: APP_JSON_KEY,
      aab: APP_BUNDLE_PATH,
      skip_upload_metadata: true,
      skip_upload_images: true,
      skip_upload_screenshots: true,
    )
  end

  def flutter_build_appBundle(versionNumber,buildNumber)
    Dir.chdir "../../" do
      sh("flutter", "packages", "get")
      sh(
        "flutter build appbundle --build-name=#{versionNumber} --build-number=#{buildNumber}"
      )
    end
  end


  def semanticValue(variable)
    if variable == "major" || variable == "minor" || variable == "patch"
      return variable
    else
      print(variable + " can not right paramater.")
      return "minor"
    end
  end

end
